use catp_layer2::{Action, AuthorizationPolicy, AuthorizationProofSystem, AuthorizationPublicInputs};
use catp_primitives::proof::Proof;
use wasm_bindgen::prelude::*;

/// Generate a ZK proof that the given action is authorized by the given policy.
///
/// All arguments are JSON strings. Returns the raw proof bytes as a Uint8Array.
///
/// JSON shapes:
///   policy:       { allowed_action, allowed_protocol, allowed_token,
///                   max_value_per_tx, max_value_total, valid_from, valid_until }
///   action:       { action_type, protocol, token, value }
///   public_inputs:{ policy_commitment, current_timestamp, cumulative_spend }
#[wasm_bindgen]
pub fn prove_authorization(
    policy_json: &str,
    action_json: &str,
    public_inputs_json: &str,
) -> Result<Vec<u8>, JsError> {
    let policy: AuthorizationPolicy =
        serde_json::from_str(policy_json).map_err(|e| JsError::new(&e.to_string()))?;
    let action: Action =
        serde_json::from_str(action_json).map_err(|e| JsError::new(&e.to_string()))?;
    let public_inputs: AuthorizationPublicInputs =
        serde_json::from_str(public_inputs_json).map_err(|e| JsError::new(&e.to_string()))?;

    let ps = AuthorizationProofSystem::new(8);
    let proof = ps
        .prove_authorization(policy, action, public_inputs)
        .map_err(|e| JsError::new(&e.to_string()))?;

    Ok(proof.0)
}

/// Verify a ZK proof previously generated by `prove_authorization`.
///
/// `proof_bytes` is the raw bytes returned by `prove_authorization`.
/// Returns true if the proof is valid, throws if it is malformed.
#[wasm_bindgen]
pub fn verify_authorization(proof_bytes: &[u8]) -> Result<bool, JsError> {
    let ps = AuthorizationProofSystem::new(8);
    let proof = Proof(proof_bytes.to_vec());
    ps.verify_authorization(&proof)
        .map_err(|e| JsError::new(&e.to_string()))
}
