use catp_layer2::{
    action_public_fields, fr_from_be_bytes, fr_to_be_bytes, native_policy_commitment, Action,
    AuthorizationPolicy, AuthorizationProofSystem, AuthorizationPublicInputs,
};
use catp_primitives::proof::Proof;
use wasm_bindgen::prelude::*;

const LAYER2_SRS: &[u8] = include_bytes!("../../layer2/catp-layer2-k12.srs");

/// Compute the Poseidon-BN254 commitment to a policy.
///
/// Returns 32 bytes in big-endian (EVM `bytes32`) format, matching what the
/// ProveAuthorization circuit exposes as `publicInputs[0]`.
#[wasm_bindgen]
pub fn compute_policy_commitment(policy_json: &str) -> Result<Vec<u8>, JsError> {
    let policy: AuthorizationPolicy =
        serde_json::from_str(policy_json).map_err(|e| JsError::new(&e.to_string()))?;
    Ok(fr_to_be_bytes(native_policy_commitment(&policy)).to_vec())
}

/// Generate a ZK proof that the given action is authorized by the given policy.
///
/// JSON shapes:
///   policy: { allowed_action, allowed_protocol, allowed_token,
///              max_value_per_tx, max_value_total, valid_from, valid_until }
///   action: { action_type, protocol, token, value }
///
/// `policy_commitment_be`: 32 bytes big-endian Fr — from `compute_policy_commitment`.
/// Returns raw proof bytes.
#[wasm_bindgen]
pub fn prove_authorization(
    policy_json: &str,
    action_json: &str,
    policy_commitment_be: &[u8],
    current_timestamp: u64,
    cumulative_spend: u64,
) -> Result<Vec<u8>, JsError> {
    let policy: AuthorizationPolicy =
        serde_json::from_str(policy_json).map_err(|e| JsError::new(&e.to_string()))?;
    let action: Action =
        serde_json::from_str(action_json).map_err(|e| JsError::new(&e.to_string()))?;

    let bytes: &[u8; 32] = policy_commitment_be
        .try_into()
        .map_err(|_| JsError::new("policy_commitment_be must be 32 bytes"))?;
    let policy_commitment = fr_from_be_bytes(bytes)
        .ok_or_else(|| JsError::new("policy_commitment_be is not a valid BN254 Fr element"))?;
    let (action_type, action_protocol, action_token, action_value) = action_public_fields(&action);

    let public_inputs = AuthorizationPublicInputs {
        policy_commitment,
        action_type,
        action_protocol,
        action_token,
        action_value,
        current_timestamp,
        cumulative_spend,
    };

    let ps = AuthorizationProofSystem::from_bytes(LAYER2_SRS)
        .map_err(|e| JsError::new(&e.to_string()))?;
    let proof = ps
        .prove_authorization(policy, action, public_inputs)
        .map_err(|e| JsError::new(&e.to_string()))?;
    Ok(proof.0)
}

/// Verify a ZK proof previously generated by `prove_authorization`.
///
/// `policy_commitment_be`: 32 bytes big-endian Fr — from `compute_policy_commitment`.
/// Returns `true` if valid, throws on malformed input.
#[wasm_bindgen]
pub fn verify_authorization(
    proof_bytes: &[u8],
    action_json: &str,
    policy_commitment_be: &[u8],
    current_timestamp: u64,
    cumulative_spend: u64,
) -> Result<bool, JsError> {
    let action: Action =
        serde_json::from_str(action_json).map_err(|e| JsError::new(&e.to_string()))?;
    let bytes: &[u8; 32] = policy_commitment_be
        .try_into()
        .map_err(|_| JsError::new("policy_commitment_be must be 32 bytes"))?;
    let policy_commitment = fr_from_be_bytes(bytes)
        .ok_or_else(|| JsError::new("policy_commitment_be is not a valid BN254 Fr element"))?;
    let (action_type, action_protocol, action_token, action_value) = action_public_fields(&action);

    let public_inputs = AuthorizationPublicInputs {
        policy_commitment,
        action_type,
        action_protocol,
        action_token,
        action_value,
        current_timestamp,
        cumulative_spend,
    };

    let ps = AuthorizationProofSystem::from_bytes(LAYER2_SRS)
        .map_err(|e| JsError::new(&e.to_string()))?;
    let proof = Proof(proof_bytes.to_vec());
    ps.verify_authorization(&proof, &public_inputs)
        .map_err(|e| JsError::new(&e.to_string()))
}
