/* tslint:disable */
/* eslint-disable */

/**
 * Compute the Poseidon-BN254 commitment to a policy.
 *
 * Returns 32 bytes in big-endian (EVM `bytes32`) format, matching what the
 * ProveAuthorization circuit exposes as `publicInputs[0]`.
 */
export function compute_policy_commitment(policy_json: string): Uint8Array;

/**
 * Generate a ZK proof that the given action is authorized by the given policy.
 *
 * JSON shapes:
 *   policy: { allowed_action, allowed_protocol, allowed_token,
 *              max_value_per_tx, max_value_total, valid_from, valid_until }
 *   action: { action_type, protocol, token, value }
 *
 * `policy_commitment_be`: 32 bytes big-endian Fr — from `compute_policy_commitment`.
 * Returns raw proof bytes.
 */
export function prove_authorization(policy_json: string, action_json: string, policy_commitment_be: Uint8Array, current_timestamp: bigint, cumulative_spend: bigint): Uint8Array;

/**
 * Verify a ZK proof previously generated by `prove_authorization`.
 *
 * `policy_commitment_be`: 32 bytes big-endian Fr — from `compute_policy_commitment`.
 * Returns `true` if valid, throws on malformed input.
 */
export function verify_authorization(proof_bytes: Uint8Array, action_json: string, policy_commitment_be: Uint8Array, current_timestamp: bigint, cumulative_spend: bigint): boolean;
