//! Proof system wrappers for the ProveAuthorization circuit — KZG/BN254 backend.
//!
//! Uses PSE halo2 with KZG/GWC commitment scheme on BN254 (Ethereum's curve).
//! Proofs use the keccak256-based EvmTranscript, making them directly verifiable
//! on-chain via the Solidity verifier generated by `cargo run --bin generate_verifier`.
//!
//! Note: `ParamsKZG::new(k)` generates a random SRS suitable for development and
//! testing. Production deployments must load SRS from the Ethereum KZG ceremony
//! (EIP-4844 powers-of-tau) via `ParamsKZG::read`. See Phase C in IMPLEMENTATION_PLAN.md.

use catp_primitives::error::{CatpError, CatpResult};
use catp_primitives::proof::Proof;
use halo2_proofs::{
    plonk::{self, keygen_pk, keygen_vk},
    poly::{
        commitment::{Params, ParamsProver},
        kzg::{
            commitment::{KZGCommitmentScheme, ParamsKZG},
            multiopen::{ProverGWC, VerifierGWC},
            strategy::SingleStrategy,
        },
    },
    transcript::{TranscriptReadBuffer, TranscriptWriterBuffer},
};
use halo2curves::bn256::{Bn256, Fr, G1Affine};
use snark_verifier::system::halo2::transcript::evm::EvmTranscript;

use crate::circuit::{AuthorizationPublicInputs, ProveAuthorization};
use crate::types::{Action, AuthorizationPolicy};

/// The Halo2-based authorization proof system (KZG/BN254).
pub struct AuthorizationProofSystem {
    params: ParamsKZG<Bn256>,
}

impl AuthorizationProofSystem {
    /// Create a new proof system with a random SRS of size 2^k rows.
    /// k=12 (4096 rows) is required for in-circuit Poseidon-3-2 over the policy
    /// fields and the 13 public authorization inputs.
    /// Intended for development and testing only — random SRS cannot be used
    /// to verify proofs on-chain.
    pub fn new(k: u32) -> Self {
        Self {
            params: ParamsKZG::<Bn256>::new(k),
        }
    }

    /// Load a proof system from a serialized SRS file written by `generate_verifier`.
    /// The SRS must have been generated with k=12. Use this in production so that
    /// proofs verify against the off-chain Halo2 verifier path.
    pub fn from_file(path: &std::path::Path) -> CatpResult<Self> {
        let mut f =
            std::fs::File::open(path).map_err(|e| CatpError::Serialization(e.to_string()))?;
        Self::from_reader(&mut f)
    }

    /// Load a proof system from serialized SRS bytes.
    pub fn from_bytes(bytes: &[u8]) -> CatpResult<Self> {
        let mut cursor = std::io::Cursor::new(bytes);
        Self::from_reader(&mut cursor)
    }

    fn from_reader(reader: &mut impl std::io::Read) -> CatpResult<Self> {
        let params = ParamsKZG::<Bn256>::read(reader)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;
        Ok(Self { params })
    }

    /// Generate a ZK proof that `action` is authorized by `policy`.
    ///
    /// `public_inputs.policy_commitment` must equal `native_policy_commitment(&policy)`.
    /// The prover will fail to verify if this invariant is violated.
    pub fn prove_authorization(
        &self,
        policy: AuthorizationPolicy,
        action: Action,
        public_inputs: AuthorizationPublicInputs,
    ) -> CatpResult<Proof> {
        let empty_circuit = ProveAuthorization::default();
        let vk = keygen_vk(&self.params, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;
        let pk = keygen_pk(&self.params, vk, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;

        let instance = build_instance(&public_inputs);
        let circuit = ProveAuthorization {
            policy: Some(policy),
            action: Some(action),
            public_inputs: Some(public_inputs),
        };

        let mut transcript = TranscriptWriterBuffer::<_, G1Affine, _>::init(vec![]);
        plonk::create_proof::<
            KZGCommitmentScheme<Bn256>,
            ProverGWC<_>,
            _,
            _,
            EvmTranscript<_, _, _, _>,
            _,
        >(
            &self.params,
            &pk,
            &[circuit],
            &[&[instance.as_slice()]],
            rand::rngs::OsRng,
            &mut transcript,
        )
        .map_err(|e| CatpError::Serialization(e.to_string()))?;

        Ok(Proof(transcript.finalize()))
    }

    /// Verify a ZK proof. Public inputs must match those used during proving.
    pub fn verify_authorization(
        &self,
        proof: &Proof,
        public_inputs: &AuthorizationPublicInputs,
    ) -> CatpResult<bool> {
        let empty_circuit = ProveAuthorization::default();
        let vk = keygen_vk(&self.params, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;

        let instance = build_instance(public_inputs);
        let params_verifier = self.params.verifier_params();
        let strategy = SingleStrategy::new(params_verifier);
        let mut transcript = TranscriptReadBuffer::<_, G1Affine, _>::init(proof.0.as_slice());

        plonk::verify_proof::<
            KZGCommitmentScheme<Bn256>,
            VerifierGWC<_>,
            _,
            EvmTranscript<_, _, _, _>,
            _,
        >(
            params_verifier,
            &vk,
            strategy,
            &[&[instance.as_slice()]],
            &mut transcript,
        )
        .map(|_| true)
        .map_err(|e| CatpError::Serialization(e.to_string()))
    }
}

/// Build the flat instance vector:
/// [commitment, action_type, protocol[4], token[4], value, timestamp, spend].
fn build_instance(pub_in: &AuthorizationPublicInputs) -> Vec<Fr> {
    let mut instance = Vec::with_capacity(13);
    instance.push(pub_in.policy_commitment);
    instance.push(Fr::from(pub_in.action_type));
    instance.extend(pub_in.action_protocol.iter().copied().map(Fr::from));
    instance.extend(pub_in.action_token.iter().copied().map(Fr::from));
    instance.push(Fr::from(pub_in.action_value));
    instance.push(Fr::from(pub_in.current_timestamp));
    instance.push(Fr::from(pub_in.cumulative_spend));
    instance
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::circuit::{action_public_fields, native_policy_commitment};
    use crate::types::{Action, ActionType, AuthorizationPolicy};

    fn test_policy() -> AuthorizationPolicy {
        AuthorizationPolicy {
            allowed_action: ActionType::Swap,
            allowed_protocol: [1u8; 32],
            allowed_token: [2u8; 32],
            max_value_per_tx: 1000,
            max_value_total: 10000,
            valid_from: 1000,
            valid_until: 9000,
        }
    }

    fn test_action() -> Action {
        Action {
            action_type: ActionType::Swap,
            protocol: [1u8; 32],
            token: [2u8; 32],
            value: 500,
        }
    }

    fn test_public_inputs() -> AuthorizationPublicInputs {
        let (action_type, action_protocol, action_token, action_value) =
            action_public_fields(&test_action());
        AuthorizationPublicInputs {
            policy_commitment: native_policy_commitment(&test_policy()),
            action_type,
            action_protocol,
            action_token,
            action_value,
            current_timestamp: 5000,
            cumulative_spend: 2000,
        }
    }

    #[test]
    fn prove_and_verify_roundtrip() {
        let ps = AuthorizationProofSystem::new(12);
        let pub_in = test_public_inputs();
        let proof = ps
            .prove_authorization(test_policy(), test_action(), pub_in.clone())
            .unwrap();
        assert!(!proof.0.is_empty());
        assert!(ps.verify_authorization(&proof, &pub_in).unwrap());
    }

    #[test]
    fn tampered_proof_fails_verification() {
        let ps = AuthorizationProofSystem::new(12);
        let pub_in = test_public_inputs();
        let mut proof = ps
            .prove_authorization(test_policy(), test_action(), pub_in.clone())
            .unwrap();
        proof.0[0] ^= 0xFF;
        assert!(ps.verify_authorization(&proof, &pub_in).is_err());
    }
}
