//! Proof system wrappers for the ProveAuthorization circuit — KZG/BN254 backend.
//!
//! Uses PSE halo2 with KZG/GWC commitment scheme on BN254 (Ethereum's curve).
//! Proofs use the keccak256-based EvmTranscript, making them directly verifiable
//! on-chain via the Solidity verifier generated by `cargo run --bin generate_verifier`.
//!
//! Note: `ParamsKZG::new(k)` generates a random SRS suitable for development and
//! testing. Production deployments must load SRS from the Ethereum KZG ceremony
//! (EIP-4844 powers-of-tau) via `ParamsKZG::read`.

use catp_primitives::error::{CatpError, CatpResult};
use catp_primitives::proof::Proof;
use halo2_proofs::{
    plonk::{self, keygen_pk, keygen_vk},
    poly::{
        commitment::ParamsProver,
        kzg::{
            commitment::{KZGCommitmentScheme, ParamsKZG},
            multiopen::{ProverGWC, VerifierGWC},
            strategy::SingleStrategy,
        },
    },
    transcript::{TranscriptReadBuffer, TranscriptWriterBuffer},
};
use halo2curves::bn256::{Bn256, G1Affine};
use snark_verifier::system::halo2::transcript::evm::EvmTranscript;

use crate::circuit::{AuthorizationPublicInputs, ProveAuthorization};
use crate::types::{Action, AuthorizationPolicy};

/// The Halo2-based authorization proof system (KZG/BN254).
pub struct AuthorizationProofSystem {
    params: ParamsKZG<Bn256>,
}

impl AuthorizationProofSystem {
    /// Create a new proof system. `k` controls circuit size: 2^k rows.
    /// k=8 (256 rows) is sufficient for ProveAuthorization.
    ///
    /// Uses a randomly generated SRS. For production, load from the Ethereum
    /// KZG ceremony file with `ParamsKZG::read`.
    pub fn new(k: u32) -> Self {
        Self {
            params: ParamsKZG::<Bn256>::new(k),
        }
    }

    /// Generate a ZK proof that `action` is authorized by `policy`.
    pub fn prove_authorization(
        &self,
        policy: AuthorizationPolicy,
        action: Action,
        public_inputs: AuthorizationPublicInputs,
    ) -> CatpResult<Proof> {
        let empty_circuit = ProveAuthorization::default();
        let vk = keygen_vk(&self.params, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;
        let pk = keygen_pk(&self.params, vk, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;

        let circuit = ProveAuthorization {
            policy: Some(policy),
            action: Some(action),
            public_inputs: Some(public_inputs),
        };

        let mut transcript = TranscriptWriterBuffer::<_, G1Affine, _>::init(vec![]);
        plonk::create_proof::<KZGCommitmentScheme<Bn256>, ProverGWC<_>, _, _, EvmTranscript<_, _, _, _>, _>(
            &self.params,
            &pk,
            &[circuit],
            &[&[&[], &[]]],
            rand::rngs::OsRng,
            &mut transcript,
        )
        .map_err(|e| CatpError::Serialization(e.to_string()))?;

        Ok(Proof(transcript.finalize()))
    }

    /// Verify a ZK proof for the ProveAuthorization circuit.
    pub fn verify_authorization(&self, proof: &Proof) -> CatpResult<bool> {
        let empty_circuit = ProveAuthorization::default();
        let vk = keygen_vk(&self.params, &empty_circuit)
            .map_err(|e| CatpError::Serialization(e.to_string()))?;

        let params_verifier = self.params.verifier_params();
        let strategy = SingleStrategy::new(params_verifier);
        let mut transcript = TranscriptReadBuffer::<_, G1Affine, _>::init(proof.0.as_slice());

        plonk::verify_proof::<KZGCommitmentScheme<Bn256>, VerifierGWC<_>, _, EvmTranscript<_, _, _, _>, _>(
            params_verifier,
            &vk,
            strategy,
            &[&[&[], &[]]],
            &mut transcript,
        )
        .map(|_| true)
        .map_err(|e| CatpError::Serialization(e.to_string()))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::types::{Action, ActionType, AuthorizationPolicy};

    fn test_policy() -> AuthorizationPolicy {
        AuthorizationPolicy {
            allowed_action: ActionType::Swap,
            allowed_protocol: [1u8; 32],
            allowed_token: [2u8; 32],
            max_value_per_tx: 1000,
            max_value_total: 10000,
            valid_from: 1000,
            valid_until: 9000,
        }
    }

    fn test_action() -> Action {
        Action {
            action_type: ActionType::Swap,
            protocol: [1u8; 32],
            token: [2u8; 32],
            value: 500,
        }
    }

    fn test_public_inputs() -> AuthorizationPublicInputs {
        AuthorizationPublicInputs {
            policy_commitment: [0u8; 32],
            current_timestamp: 5000,
            cumulative_spend: 2000,
        }
    }

    #[test]
    fn prove_and_verify_roundtrip() {
        let ps = AuthorizationProofSystem::new(8);
        let proof = ps
            .prove_authorization(test_policy(), test_action(), test_public_inputs())
            .unwrap();
        assert!(!proof.0.is_empty());
        assert!(ps.verify_authorization(&proof).unwrap());
    }

    #[test]
    fn tampered_proof_fails_verification() {
        let ps = AuthorizationProofSystem::new(8);
        let mut proof = ps
            .prove_authorization(test_policy(), test_action(), test_public_inputs())
            .unwrap();
        proof.0[0] ^= 0xFF;
        assert!(ps.verify_authorization(&proof).is_err());
    }
}
